---
deployment:
  tasks:
    - export DEPLOYPATH=/home/workstone/public_html/ridhesh-bhati/
    - /bin/cp -R backend $DEPLOYPATH
    - /bin/cp -R frontend $DEPLOYPATH
    - /bin/cp package.json $DEPLOYPATH
    - /bin/cp server.js $DEPLOYPATH
    - /bin/cp -R frontend/build/* /home/workstone/public_html/
